version: "3.7"

services:
  php:
    build:
      args:
        user: ${CONTAINER_USER}
        uid: ${CONTAINER_USER_ID}
      context: .
      dockerfile: ./docker/images/php/DockerFile
    image: grpc-demo-php
    container_name: grpc-demo-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./php-client:/var/www
    networks:
      - grpc-demo-network

  node:
    build:
      args:
        user: ${CONTAINER_USER}
        uid: ${CONTAINER_USER_ID}
      context: .
      dockerfile: ./docker/images/node/DockerFile
    image: grpc-demo-node
    container_name: grpc-demo-node
    volumes:
      - ./node-server:/usr/src/app
    networks:
      - grpc-demo-network

  nginx:
    image: nginx:1.19.1-alpine
    container_name: grpc-demo-nginx
    restart: unless-stopped
    ports:
      - 3333:3333
    volumes:
      - ./php-client:/var/www
      - ./docker/images/nginx:/etc/nginx/conf.d
    networks:
      - grpc-demo-network

networks:
  grpc-demo-network:
    driver: bridge
