<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace GPBMetadata;

class Services
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97010a0e73657276696365732e70726f746f22140a0447756964120c0a0467756964180120012809223c0a0455736572120a0a026964180120012809120d0a05656d61696c180220012809120c0a046e616d65180320012809120b0a0361676518042001280532290a0c55736572446174616261736512190a074765745573657212052e477569641a052e557365722200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

