FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

RUN pecl install grpc
COPY "./images/php/custom-ini/docker-php-ext-grpc.ini" "$PHP_INI_DIR/conf.d/"

RUN pecl install protobuf
COPY "./images/php/custom-ini/docker-php-ext-protobuf.ini" "$PHP_INI_DIR/conf.d/"

COPY './images/php/packages/protobuf-3.14.0' '~/Downloads/protobuf-3.14.0'

WORKDIR /var/www

USER $user
